import sys
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime

def generate_pdf(
    output_path,
    patient_name,
    scan_id,
    prediction,
    confidence,
    model_name,
    model_accuracy,
):
    c = canvas.Canvas(output_path, pagesize = A4)

    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, 800, "Cancer Analysis AI Report")

    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, 755, "Patient and Scan Details")

    c.setFont("Helvetica", 12)
    c.drawString(50, 730, f"Patient Name: {patient_name}")
    c.drawString(50, 710, f"Scan ID: {scan_id}")
    c.drawString(50, 690, f"Generated At: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, 650, "AI Analysis Result")

    c.setFont("Helvetica", 12)
    c.drawString(50, 625, f"Prediction: {prediction}")
    c.drawString(50, 605, f"Confidence: {confidence}%")

    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, 565, "Model Information")

    c.setFont("Helvetica", 12)
    c.drawString(50, 540, f"Model: {model_name}")
    c.drawString(50, 520, f"Evaluation Accuracy: {model_accuracy}%")

    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, 475, "Important Note")

    c.setFont("Helvetica", 11)
    c.drawString(50, 450, "This report is generated by an AI-assisted prototype.")
    c.drawString(50, 432, "It is intended for educational and decision-support demonstration only.")
    c.drawString(50, 414, "Final interpretation should be performed by a qualified medical professional.")

    c.save()

if __name__ == "__main__":
    output_path = sys.argv[1]
    patient_name = sys.argv[2]
    scan_id = sys.argv[3]
    prediction = sys.argv[4]
    confidence = sys.argv[5]
    model_name = sys.argv[6]
    model_accuracy = sys.argv[7]

    generate_pdf(
        output_path,
        patient_name,
        scan_id,
        prediction,
        confidence,
        model_name,
        model_accuracy,
    )